Code review
Mehdi-Rh/2-Code-review pull request #1
Opened 2021-12-06 14:14 UTC by Mehdi-Rh

This is a pull request that allows me to review an old trial project done in the microverse application process.

2021-12-06 15:54 UTC, Mehdi-Rh reviewed
STATUS: CHANGES REQUIRED
Hello @Mehdi-Rh 
Great job so far!
There are still some issues that should be improved but you are almost there

# Required changes

*Check the comments under the review.*
Cheers and Happy coding! 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2021-12-06 15:54 UTC, Mehdi-Rh commented on css/style.css
> +  padding-bottom: 15px;
I suggest centering items on the navigation bar.

```suggestion
  You can put    `padding: 15px;` instead of `padding-bottom: 15px;` 
```
![Screenshot from 2021-12-06 16-28-00](https://user-images.githubusercontent.com/62058680/144874612-58ec5cef-0162-4e28-a310-416f351a5b3d.png)

2021-12-06 15:54 UTC, Mehdi-Rh commented on css/style.css
> +  width: 100%;
![Screenshot from 2021-12-06 16-37-54](https://user-images.githubusercontent.com/62058680/144876117-6eb736e8-97e1-429f-a043-5f02132b1e98.png)
There is a hole in the project section
```suggestion
  I think it should be better to use grid or flexbox layout to fix this issue
```

2021-12-06 16:22 UTC, elyor-doniyorov requested changes
Hi @Mehdi-Rh, 

Good job so far!

## To highlight 👏 
-  You wrote at least 2 comments in the review 
- You used the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-06 16:22 UTC, elyor-doniyorov commented on css/style.css
> +  padding-bottom: 15px;
- [ ] I think it would be better to explain your suggestions by using GitHub inline comments feature instead of directly writing on the style.css file. Because this may confuse the student.

2021-12-06 16:22 UTC, elyor-doniyorov commented on css/style.css
> +  width: 100%;
- [ ] Great job being polite in your reviews 👍 . But kindly follow my first comment, please. Let's use GitHub inline comments feature here too.

2021-12-06 21:16 UTC, Mehdi-Rh commented on css/style.css
> +  padding-bottom: 15px;
I don't understand I have written nothing on the .css file, this is the GitHub comment !!!

2021-12-09 07:46 UTC, elyor-doniyorov approved these changes
Hi @Mehdi-Rh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 07:50 UTC, merged